# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170320_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrole',
            name='privilege',
            field=models.CharField(choices=[('REP', 'Representative'), ('MEM', 'Member')], default='MEM', max_length=3),
        ),
    ]
