# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170920_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='collaborating_clubs',
            new_name='clubs',
        ),
    ]
