# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-10 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clubrole_privilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Club'),
            preserve_default=False,
        ),
    ]
